# MkDocs configuration for Netlify builds

INHERIT: mkdocs-base.yml


site_url: https://docs.percona.com/percona-server-for-mongodb/


#Google Analytics configuration 
extra:
  analytics:
    provider: google
    property: UA-343802-3

