name: Build Percona Server for MongoDB 6.0 docs
on:
  push:
    branches: 
      - 6.0
     
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps: 
      #Pull the latest changes
      - name: Chekout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #Prepare the env
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      #Configure git
      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"
          git config user.password "${ROBOT_TOKEN}"
          echo "GIT_USER=percona-platform-robot:${ROBOT_TOKEN}" >> $GITHUB_ENV

      #Set up MkDocs
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

     
     # Deploy docs
      - name: Deploy docs
        run: |
          mike deploy 6.0 -b publish -p
          mike retitle 6.0 "6.0.14-11" -b publish -p


